stages:
  - build
  - test

build:
  stage: build
  script:
    - pip install -r requirements.txt  # Installiere Abhängigkeiten

test:
  stage: test
  script:
    - pytest  # Führe Tests mit pytest aus
