stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt  # Installiere Abhängigkeiten

test:
  stage: test
  script:
    - pytest  # Führe Tests mit pytest aus

deploy:
  stage: deploy
  script:
    - docker build -t $DOCKER_USERNAME/app_4:latest .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/app_4:latest
